# Generated by Django 4.0.4 on 2022-06-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Market_Focus', models.CharField(max_length=2)),
                ('Pull_Date', models.DateTimeField()),
                ('Dispenary_base_leaf_url', models.CharField(max_length=400)),
                ('Dispensary', models.TextField()),
                ('Name_Tag', models.CharField(max_length=100)),
                ('Member_Since', models.DecimalField(decimal_places=6, max_digits=10)),
                ('License', models.CharField(max_length=100)),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
