# Generated by Django 4.0.4 on 2022-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='id',
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='Dispenary_base_leaf_url',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
