# Generated by Django 4.0.4 on 2022-06-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaries', '0002_remove_dispensary_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensary_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dispensary', models.TextField()),
                ('total_products', models.FloatField()),
                ('Dispenary_base_leaf_url', models.CharField(max_length=400)),
                ('Last_update', models.CharField(max_length=30)),
                ('Total_Followers', models.FloatField()),
                ('Leafly_review_count', models.FloatField()),
                ('ggl_score', models.FloatField()),
                ('ggl_number_of_reviews', models.FloatField()),
                ('Pull_Date', models.DateTimeField()),
            ],
        ),
    ]
