# Generated by Django 4.0.4 on 2022-06-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaries', '0003_dispensary_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensary_time',
            old_name='Pull_Date',
            new_name='time',
        ),
    ]
