# Generated by Django 4.0.4 on 2022-06-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaries', '0004_rename_pull_date_dispensary_time_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary_time',
            name='id',
        ),
        migrations.AlterField(
            model_name='dispensary_time',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
