# Generated by Django 4.0.4 on 2022-06-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispensaries', '0005_remove_dispensary_time_id_alter_dispensary_time_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensary',
            old_name='Dispensary',
            new_name='Dispensary_name',
        ),
        migrations.RenameField(
            model_name='dispensary_time',
            old_name='Dispensary',
            new_name='Dispensary_name',
        ),
        migrations.AlterField(
            model_name='dispensary_time',
            name='Dispenary_base_leaf_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensaries.dispensary'),
        ),
    ]
