# Generated by Django 4.0.4 on 2022-06-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
