# Generated by Django 4.0.4 on 2022-06-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0002_rename_states_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('zip_code', models.CharField(default='tbd', max_length=20, primary_key=True, serialize=False)),
                ('primary_city', models.CharField(default='tbd', max_length=20)),
                ('State', models.CharField(default='tbd', max_length=20)),
                ('county', models.CharField(default='tbd', max_length=20)),
                ('timezone', models.CharField(default='tbd', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('irs_estimated_population', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_N_1_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_E_1_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_S_1_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_W_1_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('market_zips_1_miles', models.TextField(blank=True, default='tbd', null=True)),
                ('Population_with_in_1_miles', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_N_5_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_E_5_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_S_5_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_W_5_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('market_zips_5_miles', models.TextField(blank=True, default='tbd', max_length=20, null=True)),
                ('Population_with_in_5_miles', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_N_10_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_E_10_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_S_10_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_W_10_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('market_zips_10_miles', models.TextField(blank=True, default='tbd', null=True)),
                ('Population_with_in_10_miles', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_N_25_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_E_25_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_S_25_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_W_25_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('market_zips_25_miles', models.TextField(blank=True, default='tbd', null=True)),
                ('Population_with_in_25_miles', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_N_50_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_E_50_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_S_50_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_W_50_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('market_zips_50_miles', models.TextField(blank=True, default='tbd', null=True)),
                ('Population_with_in_50_miles', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_N_100_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_E_100_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_S_100_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_W_100_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('market_zips_100_miles', models.TextField(blank=True, default='tbd', null=True)),
                ('Population_with_in_100_miles', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_N_250_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_E_250_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_S_250_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('bound_W_250_miles_lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('market_zips_250_miles', models.TextField(blank=True, default='tbd', null=True)),
                ('Population_with_in_250_miles', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
            ],
        ),
    ]
