# Generated by Django 4.0.4 on 2022-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0003_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='Population_with_in_10_miles',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='Population_with_in_1_miles',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='Population_with_in_250_miles',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='Population_with_in_25_miles',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='Population_with_in_50_miles',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='Population_with_in_5_miles',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='State',
            field=models.CharField(blank=True, default='tbd', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_E_100_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_E_10_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_E_1_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_E_25_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_E_50_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_E_5_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_N_100_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_N_10_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_N_1_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_N_25_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_N_50_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_N_5_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_S_100_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_S_10_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_S_1_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_S_25_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_S_50_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_S_5_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_W_100_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_W_10_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_W_1_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_W_25_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_W_50_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='bound_W_5_miles_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='county',
            field=models.CharField(blank=True, default='tbd', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='irs_estimated_population',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='market_zips_5_miles',
            field=models.TextField(blank=True, default='tbd', null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='primary_city',
            field=models.CharField(blank=True, default='tbd', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='timezone',
            field=models.CharField(blank=True, default='tbd', max_length=20, null=True),
        ),
    ]
