# Generated by Django 4.0.4 on 2022-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0005_alter_zip_population_with_in_100_miles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='county',
            field=models.CharField(blank=True, default='tbd', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='primary_city',
            field=models.CharField(blank=True, default='tbd', max_length=100, null=True),
        ),
    ]
