# Generated by Django 4.0.4 on 2022-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0006_alter_zip_county_alter_zip_primary_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='timezone',
            field=models.CharField(blank=True, default='tbd', max_length=100, null=True),
        ),
    ]
