# Generated by Django 4.0.4 on 2022-06-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('COMPANY', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('TYPE', models.CharField(default='tbd', max_length=20)),
                ('Pull_Date', models.DateTimeField()),
                ('google_map', models.CharField(default='tbd', max_length=400)),
                ('Street', models.CharField(default='tbd', max_length=100)),
                ('Town', models.CharField(default='tbd', max_length=100)),
                ('ggl_Zip', models.CharField(default='tbd', max_length=12)),
                ('State', models.CharField(default='tbd', max_length=2)),
                ('Email', models.CharField(default='tbd', max_length=100)),
                ('Phone', models.CharField(default='tbd', max_length=100)),
                ('Website', models.CharField(default='tbd', max_length=200)),
                ('ACTIVE_on_LEAFLY', models.CharField(default='tbd', max_length=10)),
                ('Best_Google_Map_Url', models.CharField(default='tbd', max_length=400)),
                ('lat', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('ggl_name', models.TextField(default='tbd', max_length=100)),
                ('Confidence', models.CharField(default='tbd', max_length=10)),
                ('ggl_Street', models.CharField(default='tbd', max_length=100)),
                ('ggl_Town', models.CharField(default='tbd', max_length=100)),
                ('ggl_State', models.CharField(default='tbd', max_length=2)),
                ('ggl_Website', models.CharField(default='tbd', max_length=100)),
                ('ggl_Phone', models.CharField(default='tbd', max_length=100)),
                ('CLIENTa', models.CharField(default='tbd', max_length=10)),
            ],
        ),
    ]
