# Generated by Django 4.0.4 on 2022-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_clienta_company_client_alter_company_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='State',
            field=models.CharField(default='tbd', max_length=5),
        ),
    ]
