# Generated by Django 4.0.4 on 2022-06-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ggl_Zip',
            new_name='zip_code',
        ),
    ]
