# Generated by Django 4.0.4 on 2022-06-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0007_alter_zip_timezone'),
        ('companies', '0008_rename_ggl_zip_company_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geos.zip'),
        ),
    ]
