# Generated by Django 4.0.4 on 2022-05-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=100)),
                ('TYPE', models.CharField(max_length=20)),
                ('Pull_Date', models.DateField()),
                ('Dispenary_base_leaf_url', models.CharField(max_length=400)),
                ('google_map', models.CharField(max_length=400)),
                ('Street', models.CharField(max_length=100)),
                ('Town', models.CharField(max_length=100)),
                ('ggl_Zip', models.CharField(max_length=12)),
                ('State', models.CharField(max_length=2)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Website', models.CharField(max_length=200)),
                ('ACTIVE_on_LEAFLY', models.BooleanField()),
                ('Best_Google_Map_Url', models.CharField(max_length=400)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ggl_name', models.CharField(max_length=100)),
                ('Confidence', models.BooleanField()),
                ('ggl_Address', models.CharField(max_length=100)),
                ('ggl_Street', models.CharField(max_length=100)),
                ('ggl_Town', models.CharField(max_length=100)),
                ('ggl_State', models.CharField(max_length=2)),
                ('ggl_Website', models.CharField(max_length=100)),
                ('ggl_Phone', models.CharField(max_length=20)),
                ('CLIENT', models.BooleanField()),
            ],
        ),
    ]
