# Generated by Django 4.0.4 on 2022-05-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Pull_Date',
            field=models.DateTimeField(),
        ),
    ]
