# Generated by Django 4.0.4 on 2022-05-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_pull_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Company',
            new_name='COMPANY',
        ),
        migrations.AlterField(
            model_name='company',
            name='ACTIVE_on_LEAFLY',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='CLIENT',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='Confidence',
            field=models.CharField(max_length=10),
        ),
    ]
