# Generated by Django 4.0.4 on 2022-05-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_company_company_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ggl_Address',
        ),
    ]
