# Generated by Django 4.0.4 on 2022-05-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_ggl_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='COMPANY',
            field=models.CharField(max_length=300),
        ),
    ]
