# Generated by Django 4.0.4 on 2022-05-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='COMPANY',
            field=models.TextField(),
        ),
    ]
