# Generated by Django 4.0.4 on 2022-05-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ggl_name',
            field=models.TextField(max_length=100),
        ),
    ]
