# Generated by Django 4.0.4 on 2022-05-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_ggl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='ggl_Phone',
            field=models.CharField(max_length=50),
        ),
    ]
