from django.db import models

# Create your models here.

class State(models.Model):
    Name    =   models.CharField(max_length=30)
    State   =   models.CharField(max_length=2,primary_key=True)
    Capital =   models.CharField(max_length=50)

class Zip(models.Model):
    zip_code                        =   models.CharField(primary_key=True,max_length=20, default="tbd")
    primary_city                    =   models.CharField(max_length=100, default="tbd",null=True, blank=True)
    State                           =   models.CharField(max_length=20, default="tbd",null=True, blank=True)
    county                          =   models.CharField(max_length=100, default="tbd",null=True, blank=True)
    timezone                        =   models.CharField(max_length=100, default="tbd",null=True, blank=True)
    latitude                        =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    longitude                       =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    irs_estimated_population        =   models.FloatField(default=1,null=True, blank=True)
    bound_N_1_miles_lat             =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_E_1_miles_lat             =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_S_1_miles_lat             =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_W_1_miles_lat             =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    market_zips_1_miles             =   models.TextField(default="tbd",null=True, blank=True)
    Population_with_in_1_miles      =   models.FloatField(default=1,null=True, blank=True)
    bound_N_5_miles_lat             =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_E_5_miles_lat             =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_S_5_miles_lat             =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_W_5_miles_lat             =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    market_zips_5_miles             =   models.TextField(default="tbd",null=True, blank=True)
    Population_with_in_5_miles      =   models.FloatField(default=1,null=True, blank=True)
    bound_N_10_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_E_10_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_S_10_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_W_10_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    market_zips_10_miles            =   models.TextField(default="tbd",null=True, blank=True)
    Population_with_in_10_miles     =   models.FloatField(default=1,null=True, blank=True)
    bound_N_25_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_E_25_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_S_25_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_W_25_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    market_zips_25_miles            =   models.TextField(default="tbd",null=True, blank=True)
    Population_with_in_25_miles     =   models.FloatField(default=1,null=True, blank=True)
    bound_N_50_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_E_50_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_S_50_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_W_50_miles_lat            =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    market_zips_50_miles            =   models.TextField(default="tbd",null=True, blank=True)
    Population_with_in_50_miles     =   models.FloatField(default=1,null=True, blank=True)
    bound_N_100_miles_lat           =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_E_100_miles_lat           =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_S_100_miles_lat           =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    bound_W_100_miles_lat           =   models.DecimalField(max_digits=10,decimal_places=6, default=1,null=True, blank=True)
    market_zips_100_miles           =   models.TextField(default="tbd",null=True, blank=True)
    Population_with_in_100_miles    =   models.FloatField(default=1,null=True, blank=True)
    bound_N_250_miles_lat           =   models.DecimalField(max_digits=10,decimal_places=6, default=1)
    bound_E_250_miles_lat           =   models.DecimalField(max_digits=10,decimal_places=6, default=1)
    bound_S_250_miles_lat           =   models.DecimalField(max_digits=10,decimal_places=6, default=1)
    bound_W_250_miles_lat           =   models.DecimalField(max_digits=10,decimal_places=6, default=1)
    market_zips_250_miles           =   models.TextField(default="tbd",null=True, blank=True)
    Population_with_in_250_miles    =   models.FloatField(default=1,null=True, blank=True)